import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="py-8 px-12 mb-8 border-b">
          <h1 className="font-bold text-xl">ThreadNet App</h1>
        </div>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
