#pragma once

#define TRANSPORT_MODE_TCP   1
#define TRANSPORT_MODE_UDP   2
#define TRANSPORT_MODE_MULTI 3

#define TCP_TEST_PORT   8881
#define UDP_TEST_PORT   8882
#define MULTI_TEST_PORT 8883

#define TRANSPORT_MODE_BROADCAST_PORT 8888

#define TEST_DURATION_SECONDS 30
#define TEST_DURATION_BUFFER_SECONDS 5
#define TEST_MESSAGES_PER_SECOND 10
#define TEST_NUM_MESSAGES TEST_DURATION_SECONDS * TEST_MESSAGES_PER_SECOND

#define TEST_START_PORT 8899

typedef __UINT8_TYPE__ transport_mode_t;
